### PR TITLE
Allow to get all fields Strapi

### PR DESCRIPTION
**Pull request by minhtungo**
Allow to get all fields Strapi so it will also retrieve any custom fields added

### CODE REVIEW

**Review by SGFGOV — APPROVED** [review]

**Comment by SGFGOV** [comment]
Hi Please rebase, to retest checks

**Comment by minhtungo** [comment]
Rebased

**Comment by SGFGOV** [comment]
please sign the commit :)

**Comment by minhtungo** [comment]
That weird or can you just update the code according to my changes

**Pull request merged**
