### PR TITLE
add TRANSFER_TOKEN_SALT for medusa-strapi

### PR DESCRIPTION
**Pull request by minhtungo**
remove warning

### CODE REVIEW

**Review by SGFGOV — APPROVED** [review]
Thanks for fixing this..can you please rebase to the master

**Comment by SGFGOV** [comment]
I will be able to merge after you rebate the PR

**Comment by minhtungo** [comment]
> I will be able to merge after you rebate the PR

done

**Review by SGFGOV — DISMISSED** [review]

**Review by SGFGOV — APPROVED** [review]

**Comment by SGFGOV** [comment]
Hi your commit isn't signed. please follow the steps here and sign the commit .
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Pull request closed without merging**
